[project]
name = "adaptiveiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "J-R-Paul", email = "73599839+J-R-Paul@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.2",
    "scipy>=1.15.1",
    "statsmodels>=0.14.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "pytest>=8.3.4",
]
